---
- name: Install windows updates
  hosts: all
  gather_facts: no
  tasks:
    - name: Checking and installing updates
      win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      ignore_unreachable: true