---
- name: Install windows updates
  hosts: all
  tasks:
    #- name: Checking and installing updates
    #  ansible.windows.win_updates:
    #    category_names:
    #    - SecurityUpdates
    #    - CriticalUpdates
    #    - UpdateRollups
     - name: Checking and installing updates
       ansible.windows.win_shell: c:\windows\sysWOW64\USOClient.exe StartInteractiveScan